"""
Quality API Routes

Endpoints for module catalog, lint reports, and i18n coverage.
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Query, HTTPException

logger = logging.getLogger(__name__)
# DEPRECATED: Not used by frontend. Retained for potential future use.
router = APIRouter(prefix="/quality", tags=["Quality"])


@router.get("/")
async def quality_status():
    """Get quality system status and summary."""
    return {
        "ok": True,
        "status": "active",
        "service": "quality",
        "checks": ["lint", "i18n_coverage", "catalog"],
        "last_check": None,
    }


@router.get("/json")
async def quality_json():
    """Get quality report as JSON."""
    # Check for pre-generated report
    report_paths = [
        Path("reports/lint-report.json"),
        Path("data/lint-report.json"),
        Path(".lint-report.json"),
    ]

    for report_path in report_paths:
        if report_path.exists():
            try:
                with open(report_path, "r", encoding="utf-8") as f:
                    report_data = json.load(f)
                return {"ok": True, "data": report_data}
            except Exception as e:
                logger.error(f"Error reading report: {e}")

    return {
        "ok": True,
        "data": {
            "passed": True,
            "summary": {"total": 0, "errors": 0, "warnings": 0},
            "modules": [],
        },
    }


def scrub_metadata(meta: Dict[str, Any]) -> Dict[str, Any]:
    """
    Remove internal/sensitive fields from module metadata for public API.
    """
    # Fields to include in public catalog
    public_fields = {
        "module_id",
        "module_name",
        "module_description",
        "category",
        "stability",
        "version",
        "params_schema",
        "output_schema",
        "timeout_ms",
        "retryable",
        "capabilities",
    }
    return {k: v for k, v in meta.items() if k in public_fields}


@router.get("/catalog")
async def get_public_catalog(
    category: Optional[str] = Query(None, description="Filter by category"),
    stability: Optional[str] = Query(None, description="Filter by stability"),
) -> Dict[str, Any]:
    """
    Return scrubbed public catalog.

    Only includes public modules with sensitive fields removed.
    """
    try:
        from core.modules.registry import ModuleRegistry

        all_modules = ModuleRegistry.get_all_metadata()

        # Filter to public/workflow only, remove internal fields
        public_catalog = {}
        for module_id, meta in all_modules.items():
            # Skip internal modules
            exposure = meta.get("exposure", "internal")
            if exposure == "internal":
                continue

            # Apply category filter
            if category:
                mod_category = module_id.split(".")[0] if "." in module_id else ""
                if mod_category != category:
                    continue

            # Apply stability filter
            if stability:
                mod_stability = meta.get("stability", "stable")
                if mod_stability != stability:
                    continue

            public_catalog[module_id] = scrub_metadata(meta)

        return {
            "ok": True,
            "data": public_catalog,
            "count": len(public_catalog),
        }

    except ImportError:
        return {
            "ok": False,
            "error": "Module registry not available",
            "data": {},
            "count": 0,
        }
    except Exception as e:
        logger.error(f"Error loading catalog: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/lint")
async def get_lint_report(
    format: str = Query("json", description="Report format: json or summary"),
) -> Dict[str, Any]:
    """
    Return cached lint report.

    Reports are pre-generated by CI and stored in reports/ directory.
    """
    # Check for pre-generated report
    report_paths = [
        Path("reports/lint-report.json"),
        Path("data/lint-report.json"),
        Path(".lint-report.json"),
    ]

    for report_path in report_paths:
        if report_path.exists():
            try:
                with open(report_path, "r", encoding="utf-8") as f:
                    report_data = json.load(f)

                if format == "summary":
                    # Return summary only
                    return {
                        "ok": True,
                        "data": {
                            "passed": report_data.get("passed", False),
                            "summary": report_data.get("summary", {}),
                            "by_severity": report_data.get("by_severity", {}),
                            "by_category": report_data.get("by_category", {}),
                        },
                    }

                return {"ok": True, "data": report_data}

            except Exception as e:
                logger.error(f"Error reading lint report: {e}")
                raise HTTPException(status_code=500, detail=str(e))

    # No report available
    return {
        "ok": False,
        "error": "No lint report available. Run validation to generate.",
        "data": None,
    }


@router.get("/i18n/coverage")
async def get_i18n_coverage(
    locale: str = Query("en", description="Locale to check coverage for"),
) -> Dict[str, Any]:
    """
    Return translation coverage for a locale.

    Compares locale files against the English baseline.
    """
    # Look for locales directory
    locales_paths = [
        Path("locales"),
        Path("../flyto-i18n/locales"),
        Path("data/locales"),
    ]

    locales_dir = None
    for path in locales_paths:
        if path.exists() and path.is_dir():
            locales_dir = path
            break

    if not locales_dir:
        return {
            "ok": False,
            "error": "Locales directory not found",
            "data": None,
        }

    en_dir = locales_dir / "en"
    locale_dir = locales_dir / locale

    if not en_dir.exists():
        return {
            "ok": False,
            "error": "English baseline not found",
            "data": None,
        }

    # Count keys in English baseline
    total_keys = 0
    translated_keys = 0
    coverage_by_file: Dict[str, Dict[str, int]] = {}

    for en_file in en_dir.glob("*.json"):
        try:
            with open(en_file, "r", encoding="utf-8") as f:
                en_data = json.load(f)

            en_keys = count_keys(en_data)
            total_keys += en_keys

            # Check corresponding locale file
            locale_file = locale_dir / en_file.name
            if locale_file.exists():
                with open(locale_file, "r", encoding="utf-8") as f:
                    locale_data = json.load(f)
                locale_keys = count_keys(locale_data)
                translated_keys += min(locale_keys, en_keys)
                coverage_by_file[en_file.name] = {
                    "total": en_keys,
                    "translated": min(locale_keys, en_keys),
                }
            else:
                coverage_by_file[en_file.name] = {
                    "total": en_keys,
                    "translated": 0,
                }

        except Exception as e:
            logger.warning(f"Error processing {en_file}: {e}")
            continue

    percentage = (translated_keys / total_keys * 100) if total_keys > 0 else 0

    return {
        "ok": True,
        "data": {
            "locale": locale,
            "total_keys": total_keys,
            "translated": translated_keys,
            "percentage": round(percentage, 2),
            "by_file": coverage_by_file,
        },
    }


def count_keys(data: Any, prefix: str = "") -> int:
    """Recursively count keys in a nested dict."""
    count = 0
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, dict):
                count += count_keys(value, f"{prefix}{key}.")
            else:
                count += 1
    return count
