"""Portable definitions for the built-in connection catalog."""

from services.connections.contracts import ConnectionDefinition


BUILTIN_CONNECTIONS = (
    ConnectionDefinition(
        id="http.api",
        name="HTTP API",
        description="Reusable base URL, headers, and API authentication.",
        category="api",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "base_url": {"type": "string", "format": "uri"},
                "default_headers": {"type": "object"},
                "timeout_seconds": {"type": "integer", "minimum": 1, "maximum": 600},
            },
            "required": ["base_url"],
            "additionalProperties": False,
        },
        secret_slots=("api_key", "bearer_token"),
        authentication_methods=("api-key", "bearer"),
        transport_kinds=("https",),
        module_ids=("http.request",),
    ),
    ConnectionDefinition(
        id="database.postgresql",
        name="PostgreSQL",
        description="PostgreSQL server and database settings.",
        category="database",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "host": {"type": "string"},
                "port": {"type": "integer", "minimum": 1, "maximum": 65535},
                "database": {"type": "string"},
                "ssl_mode": {"enum": ["disable", "prefer", "require", "verify-full"]},
            },
            "required": ["host", "database"],
            "additionalProperties": False,
        },
        secret_slots=("username", "password"),
        authentication_methods=("password",),
        transport_kinds=("postgresql",),
        module_ids=("database.query",),
    ),
    ConnectionDefinition(
        id="messaging.slack",
        name="Slack",
        description="Slack webhook or bot-token connection.",
        category="messaging",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "default_channel": {"type": "string"},
            },
            "additionalProperties": False,
        },
        secret_slots=("webhook_url", "bot_token"),
        authentication_methods=("webhook", "bearer"),
        transport_kinds=("https",),
        module_ids=("notification.slack.send_message",),
    ),
    ConnectionDefinition(
        id="email.smtp",
        name="SMTP",
        description="SMTP server settings for outbound email.",
        category="email",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "host": {"type": "string"},
                "port": {"type": "integer", "minimum": 1, "maximum": 65535},
                "from_address": {"type": "string"},
                "tls": {"type": "boolean"},
            },
            "required": ["host", "port"],
            "additionalProperties": False,
        },
        secret_slots=("username", "password"),
        authentication_methods=("password",),
        transport_kinds=("smtp",),
        module_ids=("notification.email.send",),
    ),
    ConnectionDefinition(
        id="ai.openai",
        name="OpenAI",
        description="OpenAI-compatible API endpoint and organization settings.",
        category="ai",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "base_url": {"type": "string", "format": "uri"},
                "organization": {"type": "string"},
                "project": {"type": "string"},
            },
            "additionalProperties": False,
        },
        secret_slots=("api_key",),
        authentication_methods=("bearer",),
        transport_kinds=("https",),
        module_ids=("api.openai.chat", "agent.tool_use"),
    ),
    ConnectionDefinition(
        id="source.github",
        name="GitHub",
        description="GitHub repository and API settings.",
        category="developer-tools",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "api_url": {"type": "string", "format": "uri"},
                "owner": {"type": "string", "minLength": 1},
                "repository": {"type": "string", "minLength": 1},
            },
            "required": ["owner", "repository"],
            "additionalProperties": False,
        },
        secret_slots=("access_token",),
        authentication_methods=("bearer",),
        transport_kinds=("https",),
    ),
    ConnectionDefinition(
        id="source.gitlab",
        name="GitLab",
        description="GitLab project and API settings.",
        category="developer-tools",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "api_url": {"type": "string", "format": "uri"},
                "project_path": {"type": "string", "minLength": 1},
            },
            "required": ["project_path"],
            "additionalProperties": False,
        },
        secret_slots=("access_token",),
        authentication_methods=("bearer",),
        transport_kinds=("https",),
    ),
    ConnectionDefinition(
        id="storage.s3",
        name="S3-compatible Object Storage",
        description="AWS S3 or compatible object storage settings.",
        category="storage",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "bucket": {"type": "string", "minLength": 1},
                "endpoint_url": {"type": "string", "format": "uri"},
                "region": {"type": "string", "minLength": 1},
            },
            "required": ["bucket"],
            "additionalProperties": False,
        },
        secret_slots=("access_key_id", "secret_access_key", "session_token"),
        authentication_methods=("access-key", "workload-identity"),
        transport_kinds=("https", "s3"),
    ),
    ConnectionDefinition(
        id="mcp.streamable-http",
        name="MCP Streamable HTTP",
        description="Model Context Protocol server using Streamable HTTP.",
        category="ai-tools",
        schema_version=1,
        config_schema={
            "type": "object",
            "properties": {
                "endpoint": {"type": "string", "format": "uri"},
                "timeout_seconds": {"type": "integer", "minimum": 1, "maximum": 600},
            },
            "required": ["endpoint"],
            "additionalProperties": False,
        },
        secret_slots=("authorization",),
        authentication_methods=("bearer", "oauth2"),
        transport_kinds=("mcp-streamable-http",),
    ),
)
