/**
 * Fork Node - Split execution into parallel branches
 *
 * All output branches fire simultaneously with the same input data.
 * Typically paired with JoinNode for synchronization.
 *
 * 5-Star: Static handles defined in backend node_config.py
 * Dynamic branch handles generated by getDynamicHandles() from params.branchCount
 */

const BRANCH_COLORS = ['#10B981', '#3B82F6', '#F59E0B', '#EC4899', '#8B5CF6', '#06B6D4', '#EF4444', '#84CC16', '#14B8A6', '#F472B6']

export default {
  type: 'fork',

  // Dynamic output handles configuration
  dynamicHandles: {
    fromParam: 'branchCount',
    position: 'right',
    idPrefix: 'source-branch-',
    colors: BRANCH_COLORS
  },

  // Generate dynamic output handles based on branchCount
  getDynamicHandles: (params) => {
    const count = params?.branchCount || 2
    const handles = []
    for (let i = 1; i <= count; i++) {
      handles.push({
        id: `source-branch-${i}`,
        position: 'right',
        color: BRANCH_COLORS[(i - 1) % BRANCH_COLORS.length],
        label: `Branch ${i}`
      })
    }
    return handles
  },

  // Default parameters
  getDefaultParams: () => ({
    branchCount: 2
  }),

  // Style
  styleClass: 'fork-node',
  isFlowControl: true,

  // Fork-specific flag
  isFork: true,

  // Parameter editor component
  paramsComponent: 'GenericParams',

  // Show add button after fork
  showAddButton: true
}
