/**
 * Merge Node - Combine multiple inputs into single output
 *
 * Strategies:
 * - first: First arriving input wins
 * - last: Last arriving input wins
 * - all: Collect all inputs into array
 *
 * 5-Star: Static handles defined in backend node_config.py
 * Dynamic input handles generated by getDynamicInputHandles() from params.inputCount
 */

const INPUT_COLORS = ['#10B981', '#3B82F6', '#F59E0B', '#EC4899', '#8B5CF6', '#06B6D4', '#EF4444', '#84CC16', '#14B8A6', '#F472B6']

export default {
  type: 'merge',

  // Dynamic input handles configuration
  dynamicInputHandles: {
    fromParam: 'inputCount',
    position: 'left',
    idPrefix: 'target-input-',
    colors: INPUT_COLORS
  },

  // Generate dynamic input handles based on inputCount
  getDynamicInputHandles: (params) => {
    const count = params?.inputCount || 2
    const handles = []
    for (let i = 1; i <= count; i++) {
      handles.push({
        id: `target-input-${i}`,
        position: 'left',
        color: INPUT_COLORS[(i - 1) % INPUT_COLORS.length],
        label: `Input ${i}`
      })
    }
    return handles
  },

  // Default parameters
  getDefaultParams: () => ({
    strategy: 'all',
    inputCount: 2
  }),

  // Style
  styleClass: 'merge-node',
  isFlowControl: true,

  // Merge-specific flag
  isMerge: true,

  // Parameter editor component
  paramsComponent: 'GenericParams',

  // Show add button after merge
  showAddButton: true
}
