/**
 * Switch Node - Multi-way branch node
 * Matches value against multiple cases with dynamic output handles
 *
 * 5-Star: Static handles defined in backend node_config.py
 * Dynamic handles generated by getDynamicHandles() from params.cases
 */

export const CASE_COLORS = ['#10B981', '#3B82F6', '#F59E0B', '#EC4899', '#8B5CF6', '#06B6D4', '#EF4444', '#84CC16']

export default {
  type: 'switch',

  // Dynamic output handles configuration (for frontend generation)
  dynamicHandles: {
    fromParam: 'cases',
    position: 'right',
    idPrefix: 'source-case-',
    colors: CASE_COLORS
  },

  // Generate dynamic output handles from cases parameter
  getDynamicHandles: (params) => {
    const cases = params?.cases || []
    return cases.map((c, index) => ({
      id: `source-case-${c.id}`,
      position: 'right',
      color: CASE_COLORS[index % CASE_COLORS.length],
      label: c.label || c.value
    }))
  },

  // Default parameters
  getDefaultParams: () => ({
    expression: '',
    cases: [
      { id: `case_${Date.now()}_1`, value: 'case1', label: 'Case 1' },
      { id: `case_${Date.now()}_2`, value: 'case2', label: 'Case 2' }
    ]
  }),

  // Styling
  styleClass: 'switch-node',
  isFlowControl: true,

  // Parameter editor component
  paramsComponent: 'FlowControlParams',

  // Show add button
  showAddButton: true
}
